/** @type {import('tailwindcss').Config} */
// Theme is a 1:1 port of the Mnemosyne Stitch design system ("Technical Density").
// Tokens mirror the generated tailwind.config Stitch emits for every screen.
module.exports = {
  content: ["./**/*.{tsx,ts,html}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#313030",
        error: "#ffb4ab",
        background: "#121317",
        "on-background": "#e3e2e7",
        tertiary: "#c8c6c5",
        "secondary-fixed-dim": "#c9c6c5",
        "surface-container-low": "#1a1b1f",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474646",
        "on-surface": "#e3e2e7",
        "tertiary-container": "#686767",
        "surface-container-highest": "#343539",
        "error-container": "#93000a",
        outline: "#918f9f",
        "on-tertiary-container": "#e9e6e6",
        "surface-bright": "#38393d",
        surface: "#121317",
        "on-primary-container": "#e7e4ff",
        "inverse-surface": "#e3e2e7",
        "surface-container-high": "#292a2e",
        "on-secondary-container": "#bab8b7",
        "outline-variant": "#464554",
        "on-primary-fixed": "#0c006a",
        "on-tertiary": "#313030",
        secondary: "#c9c6c5",
        "on-primary-fixed-variant": "#3631b4",
        "secondary-container": "#4a4949",
        primary: "#c2c1ff",
        "surface-dim": "#121317",
        "on-tertiary-fixed": "#1c1b1b",
        "primary-fixed": "#e2dfff",
        "primary-container": "#5856d6",
        "surface-container-lowest": "#0d0e12",
        "on-error": "#690005",
        "inverse-primary": "#4f4ccd",
        "on-primary": "#1c0b9f",
        "surface-tint": "#c2c1ff",
        "surface-container": "#1e1f23",
        "tertiary-fixed-dim": "#c8c6c5",
        "secondary-fixed": "#e5e2e1",
        "inverse-on-surface": "#2f3034",
        "on-tertiary-fixed-variant": "#474746",
        "on-surface-variant": "#c7c4d6",
        "primary-fixed-dim": "#c2c1ff",
        "surface-variant": "#343539",
        "tertiary-fixed": "#e5e2e1",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        xl: "40px",
        margin: "16px",
        lg: "24px",
        sm: "8px",
        base: "4px",
        xs: "4px",
        gutter: "12px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "headline-md": ["Geist"],
        "headline-lg": ["Geist"],
        "label-caps": ["Inter"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "400" }],
        "code-md": ["13px", { lineHeight: "18px", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
